### ISSUE TITLE
Without full example for React it's hard to integrate with your module

### ISSUE THREAD

**Issue by DrBls** [raphaelM-sudo/quill-emoji-mart-picker#12]
In small snipets no info about variables and how to use them

**Comment by avesgit** [comment]
yep

**Comment by raphaelM-sudo** [comment]
Quill Emoji Mart Picker is no longer under active development, since I am the only developer and I currently don't have any spare time.
Besides: This is not a question, and the module and all of its variables are very well documented.
I can only assume that you might be under the impression, that this is a standalone package - but this is a Quill Plugin, which the first sentence of my documentation states.
This means you need a wrapper for Quill (e.g. react-quill).

Despite never having worked with React, I have created an example project for you: [CodeSandbox](https://codesandbox.io/s/react-quill-emoji-mart-picker-example-yl4yl)
