### ISSUE TITLE
We can not write **bold** text

### ISSUE THREAD

**Issue by jignesh-artoon** [raphaelM-sudo/quill-emoji-mart-picker#6]
### Before 3rd *
![image](https://user-images.githubusercontent.com/60254600/84761787-94625580-afe7-11ea-858e-f9dc44e5e1e7.png)

### After 3rd *
![image](https://user-images.githubusercontent.com/60254600/84761828-a217db00-afe7-11ea-969e-f80968a11424.png)

### Note:

- We can write space or Uppercase between stars
- It happens only when we use lowercase between stars

**Comment by raphaelM-sudo** [comment]
Hi,

I haven't been maintaining this repo for a while now, since I am no longer using Quill myself but I will look into it. It probably has to do with the RegEx for emoji names but I remember leaving the word as is after the RegEx found a match was not an easy task because of the way Quill blots work.

What word are you trying to type: "\*\*bold\*\*" or just "\*bold\*"?
If it is the former it could be an easy fix.

For now I'd suggest you set the indicator to something else than "*"

**Comment by raphaelM-sudo** [comment]
Fixed in version 1.1.1.

For future reference: It is possible to extend the "Emoji" class and change attributes like  "emoticonRe" or "shortNameRe" which are the regular expressions used to find emoji unicode characters or the names.
The whole Emoji class in general can be changed to your liking :)

**Comment by jignesh-artoon** [comment]
I updated my package version to 1.1.1 but still, I am facing this issue.
@raphaelM-sudo Can you please check this?

**Comment by raphaelM-sudo** [comment]
Does the [demo](https://quill-emoji-mart-picker.netlify.com/) work for you?

**Comment by raphaelM-sudo** [comment]
Try the latest version (1.1.3) maybe. I rushed with the fix and noticed later on firefox does not yet support the look behind feature in regex'.
What other blot(s) are you using? Are you using my plugin with Angular? Is it the same output as before the update?

**Comment by jignesh-artoon** [comment]
@raphaelM-sudo, Thanks for the help. 

This issue was fixed for some specific words like '**bold*' '*test*' but not fixed for all occurrences like '*bold*'. And '*bold*' is not working on the demo page as well.

I am using this to React. I using 'quill-mention' and 'quilljs-markdown' blots in my editor.

Thanks.
